In [13]:
import pandas as pd

PATH = "/lustre/fs5/jarv_lab/scratch/adenisova/Inno_2025/tmp/"
file_name = "TOGA_ALL_new_tree_reest.txt"

rer_tree = f"{PATH}/{file_name}"

df = pd.read_csv(
    rer_tree, 
    sep = "\s+",
    names = ["gene", "tree"]
)

df.dropna(inplace=True)
df

df.to_csv(
    f"{PATH}/checked_{file_name}",
    sep = "\t",
    index = False,
    header = False
)

In [9]:
from ete3 import Tree

def canonical_topology(tree, taxa):
    """
    Приводим дерево к каноническому виду:
    - обрезаем по taxa
    - убираем длины ветвей
    - сортируем потомков
    """
    t = tree.copy()
    t.prune(taxa, preserve_branch_length=False)

    for node in t.traverse():
        node.dist = 0.0

    return t.write(format=9)  # topology-only, sorted


trees = {}
with open(rer_tree) as f:
    for line in f:
        gene, newick = line.strip().split("\t")
        trees[gene] = Tree(newick, format=1)

# выбираем эталон
ref_gene = list(trees.keys())[0]
ref_tree = trees[ref_gene]

# общий набор таксонов
common_taxa = set(ref_tree.get_leaf_names())
for t in trees.values():
    common_taxa &= set(t.get_leaf_names())

ref_topo = canonical_topology(ref_tree, common_taxa)

matching = []
discordant = []

for gene, tree in trees.items():
    try:
        topo = canonical_topology(tree, common_taxa)
        if topo == ref_topo:
            matching.append(gene)
        else:
            discordant.append(gene)
    except Exception as e:
        discordant.append(gene)

print("Согласуются:", matching)
print("Не согласуются:", discordant)

Согласуются: ['A1CF_rna-XM_421561.6', 'AACS_ENSGALT00000004577.6', 'AADAT_rna-XM_004940922.3', 'AAK1_rna-XM_015297334.2', 'AANAT_rna-XM_015295119.2', 'AARSD1_ENSGALT00000004541.7', 'AASDH_ENSGALT00000022357.6', 'AASS_rna-XM_015282251.2', 'AMH_rna-NM_205030.1', 'AMIGO3_rna-XM_025154610.1', 'AMN1_rna-XM_416368.5', 'AMOTL1_rna-XM_425649.6', 'AMOT_rna-XM_015278595.2', 'ANKS1B_rna-XM_015284697.2', 'ANKS4B_rna-XM_424609.6', 'ASB6_ENSGALT00000006983.5', 'ASB9_rna-XM_015273223.2', 'ATP11A_rna-XM_015277887.2', 'ATP11C_ENSGALT00000105191.1', 'ATP13A3_rna-XM_004943327.3', 'ATP1A1_ENSGALT00000047913.2', 'ATP1B3_ENSGALT00000107916.1', 'ATP23_rna-XM_015281404.2', 'BTBD11_ENSGALT00000082819.2', 'BTBD19_rna-XM_025153075.1', 'BTBD2_rna-XM_015299872.2', 'BTBD6_rna-XM_004936422.3', 'BTBD8_rna-XM_015290685.2', 'BTC_rna-XM_015276318.2', 'BTF3L4_ENSGALT00000017200.5', 'BTG4_rna-XM_015298002.2', 'BTRC_ENSGALT00000048079.2', 'BUB1_rna-NM_001012870.1', 'BUD13_rna-XM_015298026.2', 'BUD31_rna-XM_414798.6', 'CACYBP_ENSGALT00000007248.6', 'CADM2_rna-XM_015298395.2', 'CADPS2_rna-XM_015282164.1', 'CALB2_ENSGALT00000042987.3', 'CALCRL_ENSGALT00000004147.6', 'CDH17_rna-XM_015282915.2', 'CDH19_rna-XM_025147292.1', 'CDH22_rna-XM_417477.5', 'CDH2_rna-NM_001001615.1', 'CDH5_rna-NM_204227.1', 'CDH7_rna-NM_204187.2', 'CDH9_rna-XM_015282209.2', 'CLMN_rna-XM_015287775.2', 'CLN5_rna-NM_001282194.1', 'CLN8_rna-XM_015284835.2', 'CLOCK_rna-NM_204174.3', 'CLPTM1L_rna-NM_001012864.2', 'CLRN2_rna-XM_003641249.4', 'CLSPN_rna-XM_015297697.2', 'CLSTN2_rna-XM_015277049.2', 'CLTA_ENSGALT00000090848.1', 'CSTF1_rna-XM_025142431.1', 'CSTF3_rna-NM_001012568.1', 'CTBP2_ENSGALT00000015848.6', 'CTBS_rna-XM_422372.6', 'CTDP1_ENSGALT00000102019.1', 'CTDSPL_rna-XM_025147078.1', 'CTH_rna-XM_422542.6', 'CTNNA1_rna-XM_414513.6', 'CTNNAL1_ENSGALT00000094317.1', 'CTNNBIP1_ENSGALT00000101215.1', 'DHRS3_rna-XM_025142530.1', 'DHRS7C_ENSGALT00000081588.2', 'DHX15_ENSGALT00000023259.6', 'DHX30_ENSGALT00000105056.1', 'DHX35_ENSGALT00000005796.5', 'DHX37_rna-XM_415104.6', 'EEFSEC_rna-XM_015293368.2', 'EFCAB10_rna-XM_025153692.1', 'EFCAB1_ENSGALT00000015424.6', 'EFCAB7_rna-XM_025153265.1', 'EFHC1_rna-XM_420047.6', 'EFHD1_ENSGALT00000034383.5', 'EFNB1_rna-XM_015278194.2', 'EFR3A_rna-XM_015283122.2', 'EGF_ENSGALT00000076720.2', 'EGFL7_ENSGALT00000061354.2', 'EGFR_rna-XM_025147075.1', 'EGR1_ENSGALT00000012431.6', 'EIPR1_ENSGALT00000026430.6', 'ENSGALT00000024632.5', 'ENSGALT00000024757.6_shortIntron', 'ENSGALT00000025491.6', 'ENSGALT00000026207.6', 'ENSGALT00000026357.6', 'ENSGALT00000026816.5_shortIntron', 'ENSGALT00000027001.6', 'ENSGALT00000027125.6', 'ENSGALT00000027374.6', 'ENSGALT00000027828.5', 'ENSGALT00000027966.5', 'ENSGALT00000085361.2', 'ENSGALT00000085569.2', 'ENSGALT00000086215.2', 'ENSGALT00000087043.2', 'ENSGALT00000087421.2', 'ENSGALT00000088127.2', 'ENSGALT00000088478.2_potentialNMD', 'ENSGALT00000088719.2', 'ENSGALT00000089119.2', 'ENSGALT00000089357.2', 'ENSGALT00000089595.2', 'ENSGALT00000090527.1', 'ENSGALT00000090667.1', 'ENSGALT00000090851.1', 'ENSGALT00000091085.1', 'ENSGALT00000106363.1', 'ENSGALT00000106543.1', 'ENSGALT00000106874.1', 'ENSGALT00000107001.1', 'ENSGALT00000107460.1', 'ENSGALT00000107638.1', 'ENSGALT00000107702.1', 'ENSGALT00000107826.1', 'ENSGALT00000108354.1', 'ENTPD2_ENSGALT00000086529.2', 'ENTPD6_rna-XM_015283461.2', 'ENY2_ENSGALT00000106268.1', 'FAM204A_rna-XM_004942312.2', 'FAM208A_rna-XM_015293389.2', 'FARP1_rna-NM_001252064.2', 'FARS2_ENSGALT00000078693.2', 'FASLG_ENSGALT00000004863.5', 'FAS_rna-XM_015288351.2', 'FASTKD2_rna-XM_421951.6', 'FASTK_ENSGALT00000077037.3', 'GAS6_rna-XM_015277909.2', 'GAS8_ENSGALT00000000745.6', 'GATA3_rna-XM_015293289.2', 'GATA5_rna-XM_015296343.2', 'GATB_rna-XM_420446.6', 'GATM_ENSGALT00000038740.3', 'GBE1_rna-XM_015298401.2', 'GPLD1_ENSGALT00000091617.1', 'GPN1_rna-XM_419990.3', 'GPN3_ENSGALT00000085679.2', 'GPR107_ENSGALT00000006449.5', 'GPR12_rna-XM_025146842.1', 'GPR137B_rna-XM_015284054.2', 'GPR139_ENSGALT00000044220.3', 'GPR146_rna-XM_015294154.2', 'GPR156_rna-XM_025143459.1', 'HADH_ENSGALT00000025976.6', 'HAL_rna-XM_015283716.2', 'HAO1_ENSGALT00000014374.6', 'HAPLN1_rna-XM_015280598.2', 'HAPLN3_ENSGALT00000034015.5', 'HARS_rna-NM_001006144.1', 'HAT1_ENSGALT00000015508.6', 'HAUS2_rna-XM_015287080.2', 'HAUS6_rna-NM_001031421.1', 'HAVCR1_rna-NM_001030617.2', 'HBBA_ENSGALT00000036373.4', 'HBE1_ENSGALT00000036371.4', 'HBE_rna-NM_001081704.2', 'HTR3A_rna-XM_004948063.3', 'HTR5A_rna-XM_425970.3', 'HTR7_ENSGALT00000075301.3', 'HTRA1_rna-XM_015288895.2', 'HTRA3_rna-XM_015285845.1', 'HUNK_rna-XM_015299710.2', 'HYAL6_ENSGALT00000092538.1', 'HYPK_ENSGALT00000022561.6', 'IAPP_ENSGALT00000021509.5', 'IFT88_ENSGALT00000027679.6', 'ITPR1_rna-XM_015292941.2', 'KCND3_rna-XM_015298876.2', 'KCNE3_rna-XM_025152514.1', 'KCNF1_rna-XM_426210.5', 'KCNG4_rna-XM_425129.5', 'KCNH5_rna-XM_421414.5', 'LDLRAD4_ENSGALT00000097983.1', 'LEAP2_ENSGALT00000107397.1', 'LEF1_rna-XM_015276135.2', 'LEO1_rna-NM_001292086.2', 'LEPR_rna-NM_204323.1', 'LETM2_ENSGALT00000075639.3', 'LGALS1_ENSGALT00000020302.5', 'LGALS3_rna-NM_001302800.1', 'LGALSL_rna-NM_001008456.1', 'LGMN_rna-XM_025150853.1', 'LGR5_rna-XM_425441.5', 'LH-2A_rna-XM_015279326.2', 'LHFPL2_ENSGALT00000007061.6', 'LHPP_rna-XM_015289064.2', 'LHX4-AS1_rna-XM_025152811.1', 'LYVE1_rna-NM_001199587.1', 'LZTFL1_ENSGALT00000090893.1', 'LZTS1_rna-XM_428882.5', 'M1AP_rna-XM_004949848.3', 'MAB21L1_ENSGALT00000090221.2', 'MACC1_rna-XM_418705.6', 'MAP2_rna-XM_015289323.2', 'MAP3K14_rna-XM_015299228.2', 'MGAT4C_rna-XM_025143661.1', 'MGAT5B_rna-XM_015295283.2', 'MKRN2OS_rna-XM_414310.5', 'MLANA_ENSGALT00000031380.5', 'MLEC_rna-XM_015275414.2', 'MLF2_rna-XM_015293367.2', 'MLH3_ENSGALT00000016763.5', 'MLLT10_ENSGALT00000012873.6', 'MTHFR_rna-XM_417645.6', 'MTHFS_rna-NM_001277626.1', 'MTIF3_rna-NM_001277799.1', 'MTMR10_rna-XM_015278987.2', 'MTMR14_ENSGALT00000010655.6', 'MTMR2_rna-XM_015279951.2', 'MTMR4_rna-XM_415720.6', 'MTMR7_rna-XM_420686.6', 'MTMR9_rna-XM_015285129.2', 'NKX6-3_rna-XM_428808.6', 'NLGN1_rna-XM_015291653.2', 'NLK_rna-XM_015295865.2', 'NLRC3_rna-XM_015294675.2', 'NLRX1_rna-XM_004948038.3', 'NMD3_rna-XM_422813.6', 'NME2_ENSGALT00000034721.4', 'NME4_rna-NM_001282217.1', 'NME6_ENSGALT00000082348.2', 'NME8_rna-XM_426021.6', 'OPNP_ENSGALT00000007878.6', 'OPRK1_rna-NM_001318774.1', 'OPRM1_rna-XM_003640960.4', 'OPTN_ENSGALT00000022327.7', 'ORAI1_ENSGALT00000092866.1', 'ORC2_rna-NM_001006517.1', 'ORC4_rna-XM_422152.6', 'ORM1_ENSGALT00000008177.6', 'OSBP2_rna-XM_415293.6', 'OSBPL11_rna-XM_015289956.2', 'OSBPL2_rna-XM_025142206.1', 'PES1_rna-XM_015294929.1', 'PEX11A_rna-XM_413859.5', 'PEX12_rna-XM_415773.4', 'PEX14_rna-XM_001234696.5', 'PEX1_rna-XM_004939295.3', 'PEX2_rna-XM_015282786.2', 'PEX7_ENSGALT00000022499.6', 'PFDN4_ENSGALT00000012637.6', 'PFKL_ENSGALT00000041182.4', 'PFN2_rna-XM_015291695.2', 'PGAM1_ENSGALT00000039466.4', 'POLDIP2_rna-NM_001317356.1', 'POLE2_rna-XM_015276725.2', 'POLE_ENSGALT00000012422.6', 'POLG_rna-XM_015292047.2', 'POLK_rna-XM_015277214.2', 'PTAFR_rna-XM_004947701.3', 'PTBP1_rna-XM_015299920.2', 'PTBP3_rna-XM_015280703.2', 'PTCHD1_rna-XM_425565.6', 'PTDSS1_ENSGALT00000059601.2', 'PTEN_rna-XM_015278701.2', 'PTGES2_rna-XM_415498.6', 'PTGES_ENSGALT00000099546.1', 'PTGFR_rna-XM_025152864.1', 'PTGR2_rna-NM_001031195.2', 'RBBP8NL_rna-XM_015296652.2', 'RBFA_rna-XM_015275856.2', 'RBFOX2_rna-XM_015287962.2', 'RBKS_rna-XM_419471.6', 'RBM11_ENSGALT00000083517.2', 'RBM12_rna-NM_206986.2', 'RBM18_rna-XM_415396.6', 'RBM22_ENSGALT00000007249.4', 'RBM33_rna-XM_025148307.1', 'RBM38_rna-NM_001305093.1', 'RBM43_rna-XM_025152569.1', 'RBM46_rna-XM_420372.6', 'RBM5_ENSGALT00000051206.2', 'rna-NM_001195600.1', 'rna-NM_001197144.1', 'rna-NM_001198738.1', 'rna-NM_001199449.1', 'rna-NM_001199690.1_shortIntron', 'rna-NM_001252278.2', 'rna-XM_004936918.3', 'rna-XM_004937026.3', 'rna-XM_004937174.3', 'rna-XM_004937245.3', 'rna-XM_004937562.3', 'rna-XM_004937742.3', 'rna-XM_004937759.3_shortIntron', 'rna-XM_004937871.3', 'rna-XM_004937958.3', 'rna-XM_004938104.3', 'rna-XM_004942471.3', 'rna-XM_015278695.2', 'rna-XM_015278711.2', 'rna-XM_015278719.2', 'rna-XM_015278890.2', 'rna-XM_015278935.2', 'rna-XM_015279108.1', 'rna-XM_015279182.2', 'rna-XM_015294307.2', 'rna-XM_015294379.2', 'rna-XM_015294430.2', 'rna-XM_015294506.2', 'rna-XM_015294559.2', 'rna-XM_015294646.2', 'rna-XM_015294715.2', 'rna-XM_015294792.2', 'rna-XM_015295118.2', 'rna-XM_015295323.2', 'rna-XM_015295370.2', 'rna-XM_025145559.1_potentialNMD', 'rna-XM_025145830.1', 'rna-XM_025146592.1', 'rna-XM_025146750.1', 'rna-XM_025146859.1', 'rna-XM_025146903.1', 'rna-XM_025146941.1_shortIntron', 'rna-XM_025146998.1', 'rna-XM_416489.6', 'rna-XM_416545.6', 'rna-XM_416595.6', 'rna-XM_416617.5', 'rna-XM_416675.5', 'rna-XM_416731.6', 'rna-XM_416760.6', 'rna-XM_416785.6', 'RPS17_ENSGALT00000048891.2', 'RPS20_ENSGALT00000023311.6', 'RPS24_ENSGALT00000084442.2', 'RPS27A_rna-NM_001287205.1', 'RPS28_ENSGALT00000107789.1', 'RPS3A_rna-NM_001082417.2', 'RPS6_ENSGALT00000024329.6', 'RPS6KA2_rna-XM_025149054.1', 'RPS6KA5_ENSGALT00000081914.2', 'RPS6KC1_rna-XM_004935322.3', 'RPS7_ENSGALT00000026442.6', 'RPSAP58_ENSGALT00000082200.2', 'RPUSD1_rna-XM_003642118.3', 'RPUSD4_ENSGALT00000088029.2', 'RRAGB_rna-XM_025150476.1', 'RRAGD_ENSGALT00000043218.3', 'RRBP1_ENSGALT00000098776.1', 'RRH_rna-NM_001079759.2', 'SERPINB6_ENSGALT00000083784.2', 'SERPIND1_rna-XM_001232766.5', 'SERPINF1_rna-XM_015295746.2', 'SERPINH1_rna-NM_205291.1', 'SERTAD2_rna-XM_015278044.2', 'SESN1_rna-XM_004940327.3', 'SESN3_rna-XM_015280561.2', 'SETD1B_rna-NM_001030661.1', 'SETD4_rna-XM_015299408.2', 'SETD6_rna-XM_025154145.1', 'SLC25A30_ENSGALT00000027432.6', 'SLC31A1_rna-NM_001305659.1', 'SLC34A1_rna-XM_015293844.2', 'SLC35A2_rna-XM_015290618.2', 'SLC35B1_ENSGALT00000075312.2', 'SLC35B4_rna-XM_414994.6', 'SLC35D3_rna-XM_426171.5', 'SLC35E2B_ENSGALT00000002094.6', 'SLC35F1_rna-XM_025148947.1', 'SLC35F3_rna-XM_419560.6', 'SLC35F5_rna-XM_004942978.3', 'SLC36A1_rna-XM_004944938.3', 'SLC37A1_rna-XM_015300972.2', 'SLC37A3_rna-XM_015285544.2', 'SLC38A11_rna-XM_004942810.3', 'SLC38A2_ENSGALT00000107178.1', 'SNU13_rna-XM_015286219.1', 'SNW1_ENSGALT00000017099.6', 'SNX13_rna-XM_015281412.2', 'SNX16_rna-XM_015282793.2', 'SNX19_rna-XM_025143364.1', 'SNX20_rna-XM_025154161.1', 'SNX22_rna-XM_025154061.1', 'SOX6_rna-XM_025150674.1', 'SP3_rna-NM_204603.1', 'SPACA9_rna-XM_015279536.2', 'SPAG17_ENSGALT00000071804.2', 'SPAG6_rna-XM_025147182.1', 'STN1_rna-XM_015288718.2', 'STOML2_ENSGALT00000003212.6', 'STON1_ENSGALT00000104824.1', 'STOX2_rna-XM_004941063.3', 'STRA8_ENSGALT00000038151.5', 'STRAP_ENSGALT00000021374.5', 'SUSD6_rna-XM_421180.6', 'SV2B_rna-XM_425081.6', 'SVIL_rna-XM_015282091.2', 'SVOPL_rna-XM_004937855.3', 'TICAM1_rna-XM_015300025.2', 'TIE1_rna-XM_015291320.2', 'TIMM13_ENSGALT00000043405.3', 'TIMM44_ENSGALT00000000472.6', 'TIMM9_rna-XM_015287252.2', 'TIMP2_ENSGALT00000045529.2', 'TIMP4_ENSGALT00000091165.1', 'TINAG_rna-XM_015284831.2', 'TIPIN_rna-XM_015292095.2', 'TIRAP_ENSGALT00000086593.2', 'TJP2_ENSGALT00000053006.2', 'TK1_ENSGALT00000082171.2', 'TKFC_rna-XM_015286123.2', 'TLCD2_ENSGALT00000034972.5', 'TMTC4_rna-XM_416968.6', 'TMX4_ENSGALT00000046191.2', 'TNMD_ENSGALT00000011029.7', 'TNNC2_ENSGALT00000011060.5', 'TNNI2_ENSGALT00000010641.5', 'TNNT2_rna-XM_015298694.2', 'TNRC6A_rna-XM_015294488.2', 'TNRC6C_rna-XM_015295277.2', 'TNS3_rna-XM_015275851.2', 'TOB1_ENSGALT00000011909.7', 'TOGARAM1_rna-XM_025150887.1', 'TOM1L1_ENSGALT00000105896.1', 'TXNDC15_ENSGALT00000059219.3', 'TXNDC17_ENSGALT00000043725.3', 'TXNDC9_ENSGALT00000082985.2', 'TXNL4B_rna-NM_001278071.1', 'TXNRD2_ENSGALT00000106227.1', 'TYR_ENSGALT00000027865.6', 'TYRP1_rna-NM_205045.2', 'TYW5_ENSGALT00000013230.5', 'U2SURP_ENSGALT00000004113.6', 'UAP1L1_rna-XM_415568.6', 'UBA3_rna-XM_015293250.2', 'UBA6_rna-XM_420609.6', 'UBAC2_rna-XM_015274298.2', 'VSX2_rna-XM_025150559.1', 'VTG1_rna-NM_001004408.2', 'VTI1B_rna-XM_421192.6', 'VWA1_rna-XM_417574.6', 'VWA3A_rna-XM_025155272.1', 'VWA9_ENSGALT00000107979.1', 'VWC2L_rna-XM_025152406.1', 'VXN_rna-XM_004939886.3', 'WAPL_ENSGALT00000066476.2', 'WARS_rna-XM_421368.5', 'WASF2_rna-XM_424015.6', 'ZFYVE26_rna-XM_004941715.3', 'ZFYVE9_rna-XM_015291220.2', 'ZHX2_rna-XM_015283161.2', 'ZMAT2_ENSGALT00000064754.2', 'ZMAT4_rna-XM_015297406.2', 'ZMIZ1_rna-XM_015288283.2', 'ZMYM3_rna-XM_015278406.2']
Не согласуются: []

In [11]:
print(ref_tree)

   /-Smithornis_capensis
  |
  |--Pitta_novaeguineae
  |
  |      /-Tyrannus_savana
  |   /-|
  |  |   \-Manacus_vitellinus
  |  |
  |  |                        /-Alauda_arvensis
  |  |                       |
  |  |                       |            /-Phylloscopus_sibilatrix
  |  |                       |         /-|
  |  |                       |        |  |   /-Cettia_cetti
  |  |                     /-|        |   \-|
  |  |                    |  |      /-|      \-Aegithalos_caudatus
  |  |                    |  |     |  |
  |  |                    |  |     |  |   /-Sylvia_atricapilla
  |  |                    |  |   /-|   \-|
  |  |                    |  |  |  |      \-Leiothrix_lutea
  |  |                  /-|   \-|  |
  |  |                 |  |     |   \-Hirundo_rustica
  |  |                 |  |     |
  |  |                 |  |      \-Hippolais_icterina
  |  |                 |  |
  |  |                 |  |      /-Cyanistes_caeruleus
  |  |                 |  |   /-|
--|  |                 |   \-|   \-Parus_major
  |  |                 |     |
  |  |                 |      \-Poecile_atricapillus
  |  |                 |
  |  |                 |         /-Phainopepla_nitens
  |  |                 |      /-|
  |  |                 |     |   \-Bombycilla_garrulus
  |  |                 |     |
  |  |                 |     |                  /-Turdus_rufiventris
  |  |                 |     |               /-|
  |  |                 |     |            /-|   \-Catharus_fuscescens
  |  |               /-|     |           |  |
  |  |              |  |     |           |   \-Sialia_sialis
  |  |              |  |     |         /-|
  |  |              |  |   /-|        |  |      /-Ficedula_albicollis
  |  |              |  |  |  |        |  |   /-|
  |  |              |  |  |  |      /-|   \-|   \-Oenanthe_seebohmi
  |  |              |  |  |  |     |  |     |
  |  |              |  |  |  |     |  |      \-Erithacus_rubecula
  |  |              |  |  |  |   /-|  |
  |  |              |  |  |  |  |  |   \-Cinclus_mexicanus
  |  |              |  |  |  |  |  |
  |  |              |  |  |  |  |   \-Sturnus_vulgaris
  |  |              |  |  |   \-|
  |  |              |  |  |     |         /-Thryothorus_ludovicianus
  |  |              |  |  |     |      /-|
  |  |              |  |  |     |   /-|   \-Polioptila_caerulea
   \-|              |  |  |     |  |  |
     |              |  |  |      \-|   \-Certhia_familiaris
     |              |  |  |        |
     |              |   \-|         \-Sitta_europaea
     |            /-|     |
     |           |  |     |                  /-Geothlypis_trichas
     |           |  |     |                 |
     |           |  |     |               /-|      /-Quiscalus_mexicanus
     |           |  |     |              |  |   /-|
     |           |  |     |              |   \-|   \-Molothrus_ater
     |           |  |     |            /-|     |
     |           |  |     |           |  |      \-Agelaius_phoeniceus
     |           |  |     |         /-|  |
     |           |  |     |        |  |   \-Junco_hyemalis
     |           |  |     |      /-|  |
     |           |  |     |     |  |   \-Cardinalis_cardinalis
     |           |  |     |   /-|  |
     |           |  |     |  |  |   \-Loxia_leucoptera
     |         /-|  |     |  |  |
     |        |  |  |      \-|   \-Motacilla_alba
     |        |  |  |        |
     |        |  |  |        |   /-Passer_montanus
     |        |  |  |         \-|
     |        |  |  |            \-Passer_domesticus
     |        |  |  |
     |        |  |   \-Eopsaltria_australis
     |        |  |
     |        |  |            /-Corvus_brachyrhynchos
     |      /-|  |         /-|
     |     |  |  |      /-|   \-Lanius_ludovicianus
     |     |  |  |     |  |
     |     |  |  |   /-|   \-Parotia_helenae
     |     |  |  |  |  |
     |     |  |   \-|   \-Gymnorhina_tibicen
     |   /-|  |     |
     |  |  |  |     |   /-Falcunculus_frontatus
     |  |  |  |      \-|
     |  |  |  |         \-Oriolus_oriolus
     |  |  |  |
     |  |  |   \-Entomyzon_cyanotis
     |  |  |
     |  |   \-Ptilonorhynchus_violaceus
     |  |
     |  |   /-Acanthisitta_chloris
     |  |  |
     |  |  |                     /-Amazona_aestiva
     |  |  |                  /-|
     |  |  |                 |   \-Myiopsitta_monachus
      \-|  |                 |
        |  |                 |               /-Ara_militaris
        |  |                 |            /-|
        |  |                 |         /-|   \-Ara_macao
        |  |               /-|        |  |
        |  |              |  |      /-|   \-Ara_ararauna
        |  |              |  |     |  |
        |  |              |  |   /-|   \-Guaruba_guarouba
        |  |              |  |  |  |
        |  |              |  |  |   \-Anodorhynchus_hyacinthinus
        |  |            /-|   \-|
        |  |           |  |     |      /-Pyrrhura_molinae
        |  |           |  |     |   /-|
        |  |           |  |      \-|   \-Pyrrhura_frontalis
        |  |           |  |        |
         \-|         /-|  |         \-Pyrrhura_perlata
           |        |  |  |
           |        |  |   \-Psittacus_erithacus
           |        |  |
           |        |  |   /-Agapornis_roseicollis
           |      /-|   \-|
           |     |  |     |   /-Psittacula_krameri
           |     |  |      \-|
           |   /-|  |         \-Eclectus_roratus
           |  |  |  |
           |  |  |   \-Probosciger_aterrimus
           |  |  |
           |  |   \-Nestor_notabilis
           |  |
           |  |            /-Falco_naumanni
           |  |         /-|
           |  |        |   \-Falco_tinnunculus
           |  |      /-|
           |  |     |  |   /-Falco_peregrinus
           |  |   /-|   \-|
            \-|  |  |      \-Falco_rusticolus
              |  |  |
              |  |   \-Herpetotheres_cachinnans
              |  |
              |  |   /-Cariama_cristata
              |  |  |
              |  |  |            /-Sagittarius_serpentarius
              |  |  |           |
              |  |  |         /-|      /-Haliaeetus_albicilla
              |  |  |        |  |   /-|
              |  |  |        |   \-|   \-Haliaeetus_leucocephalus
              |  |  |      /-|     |
              |  |  |     |  |      \-Spizaetus_tyrannus
               \-|  |     |  |
                 |  |     |   \-Gymnogyps_californianus
                 |  |     |
                 |  |   /-|      /-Halcyon_senegalensis
                 |  |  |  |     |
                 |  |  |  |   /-|      /-Colaptes_auratus
                 |  |  |  |  |  |   /-|
                 |  |  |  |  |   \-|   \-Melanerpes_aurifrons
                 |  |  |   \-|     |
                 |  |  |     |      \-Ramphastos_sulfuratus
                 |  |  |     |
                 |  |  |     |   /-Bucorvus_abyssinicus
                 |  |  |      \-|
                 |  |  |         \-Upupa_marginata
                  \-|  |
                    |  |            /-Caprimulgus_europaeus
                    |  |         /-|
                    |  |        |   \-Podargus_strigoides
                    |  |        |
                    |  |        |            /-Spheniscus_humboldti
                    |  |        |         /-|
                    |  |        |        |   \-Pelecanoides_urinatrix
                    |  |        |        |
                    |  |        |        |         /-Fregata_magnificens
                    |  |        |        |        |
                    |  |      /-|      /-|      /-|      /-Nannopterum_auritum
                    |  |     |  |     |  |     |  |   /-|
                    |  |     |  |     |  |     |   \-|   \-Phalacrocorax_carbo
                    |  |     |  |     |  |   /-|     |
                    |  |     |  |     |  |  |  |      \-Anhinga_anhinga
                    |  |     |  |     |  |  |  |
                    |  |     |  |   /-|   \-|  |   /-Cochlearius_cochlearius
                    |  |     |  |  |  |     |   \-|
                    |  |     |  |  |  |     |      \-Egretta_garzetta
                    |  |     |  |  |  |     |
                    |  |     |   \-|  |      \-Ciconia_maguari
                    |  |     |     |  |
                    |  |     |     |   \-Gavia_stellata
                     \-|     |     |
                       |     |      \-Eurypyga_helias
                       |     |
                       |     |                  /-Calidris_pugnax
                       |     |               /-|
                       |     |              |   \-Arenaria_interpres
                       |     |            /-|
                       |     |           |  |   /-Jacana_jacana
                       |     |           |   \-|
                       |     |           |      \-Rostratula_benghalensis
                       |   /-|           |
                       |  |  |           |            /-Chroicocephalus_maculipennis
                       |  |  |         /-|         /-|
                       |  |  |        |  |      /-|   \-Rissa_tridactyla
                       |  |  |        |  |     |  |
                       |  |  |        |  |   /-|   \-Rynchops_niger
                       |  |  |        |  |  |  |
                       |  |  |        |  |  |  |   /-Stercorarius_parasiticus
                       |  |  |        |   \-|   \-|
                       |  |  |      /-|     |      \-Uria_lomvia
                       |  |  |     |  |     |
                       |  |  |     |  |      \-Dromas_ardeola
                       |  |  |     |  |
                       |  |  |     |  |      /-Chionis_minor
                       |  |  |     |  |   /-|
                       |  |  |     |  |  |   \-Burhinus_indicus
                       |  |  |     |  |  |
                       |  |  |     |   \-|         /-Anarhynchus_dealbatus
                       |  |  |   /-|     |      /-|
                       |  |  |  |  |     |   /-|   \-Charadrius_vociferus
                       |  |  |  |  |     |  |  |
                       |  |  |  |  |      \-|   \-Pluvialis_apricaria
                       |  |  |  |  |        |
                       |  |  |  |  |         \-Himantopus_leucocephalus
                       |  |   \-|  |
                       |  |     |  |      /-Psophia_crepitans
                        \-|     |  |   /-|
                          |     |   \-|   \-Aramus_guarauna
                          |     |     |
                          |     |      \-Fulica_atra
                          |     |
                          |      \-Opisthocomus_hoazin
                          |
                          |                  /-Columba_livia
                          |               /-|
                          |            /-|   \-Streptopelia_turtur
                          |           |  |
                          |         /-|   \-Columbina_picui
                          |        |  |
                          |      /-|   \-Caloenas_nicobarica
                          |     |  |
                          |     |   \-Pterocles_orientalis
                          |   /-|
                          |  |  |      /-Cuculus_canorus
                          |  |  |   /-|
                          |  |   \-|   \-Geococcyx_californianus
                          |  |     |
                          |  |      \-Ardeotis_kori
                          |  |
                          |  |   /-Podilymbus_podiceps
                          |  |  |
                          |  |  |            /-Anseranas_semipalmata
                          |  |  |           |
                           \-|  |           |         /-Anas_platyrhynchos
                             |  |           |      /-|
                             |  |         /-|     |   \-Aythya_fuligula
                             |  |        |  |   /-|
                             |  |        |  |  |  |      /-Branta_canadensis
                             |  |        |  |  |  |   /-|
                             |  |        |  |  |   \-|   \-Anser_cygnoides
                             |  |        |   \-|     |
                             |  |      /-|     |      \-Cygnus_olor
                             |  |     |  |     |
                             |  |     |  |     |   /-Stictonetta_naevosa
                              \-|     |  |      \-|
                                |     |  |         \-Oxyura_ferruginea
                                |     |  |
                                |     |   \-Chauna_torquata
                                |     |
                                |     |            /-Alectoris_rufa
                                |     |         /-|
                                |   /-|        |   \-Pavo_muticus
                                |  |  |        |
                                |  |  |      /-|         /-Phasianus_colchicus
                                |  |  |     |  |      /-|
                                |  |  |     |  |   /-|   \-Lophura_nycthemera
                                |  |  |     |  |  |  |
                                |  |  |     |   \-|   \-Chrysolophus_pictus
                                |  |  |   /-|     |
                                |  |  |  |  |     |   /-Centrocercus_urophasianus
                                 \-|  |  |  |      \-|
                                   |   \-|  |         \-Meleagris_gallopavo
                                   |     |  |
                                   |     |   \-Colinus_virginianus
                                   |     |
                                   |      \-Numida_meleagris
                                   |
                                   |      /-Rhea_americana
                                   |   /-|
                                    \-|   \-Casuarius_casuarius
                                      |
                                       \-Nothoprocta_perdicaria

In [ ]:
df.to_csv(
    f"{PATH}/checked_{file_name}",
    sep = "\t",
    index = False,
    header = False
)

df_genes = pd.read_csv(
    f"{PATH}/TOGA_ALL_polished_phy_stat.tsv",
    sep = "\t",
    names = ["gene","len_seq","number_of_reqs","sp_names"]
)
# df_genes = df_genes[df_genes["number_of_reqs"] > 200]

In [4]:
df.merge(df_genes, how = "inner")[["gene", "tree"]].to_csv(
    f"{PATH}/checked_{file_name}",
    sep = "\t",
    index = False,
    header = False
)

In [39]:
from ete3 import Tree

t = Tree(df[df["gene"] == "KCNE4_rna-XM_025153654.1"]["tree"].item(), format = 1)
all_leafs = set(t.get_leaf_names())

df["uniq"] = df["tree"].apply(lambda x: set(Tree(x, format = 1).get_leaf_names()) - all_leafs)

In [42]:
df[df["uniq"].apply(lambda x: len(x) > 0)]

Empty DataFrame
Columns: [gene, tree, uniq]
Index: []

KeyboardInterrupt

In [2]:
df[df["gene"] == "AACS_ENSGALT00000004577.6"]["tree"].item()

'(Tyrannus_savana:0.0491120196,Oxyruncus_cristatus:0.0325447824,((((Pipra_filicauda:0.0075016437,Manacus_vitellinus:0.0117625149)mrcaott105307ott128718:0.0058520004,Lepidothrix_velutina:0.0051029829)mrcaott49248ott105307:0.0099837890,Chiroxiphia_lanceolata:0.0182827814)mrcaott25827ott49248:0.0103075759,(Grallaria_varia:0.0631984475,((Pitta_sordida:0.0540914173,Smithornis_capensis:0.0475988127)mrcaott33874ott50165:0.0221558033,((((((((((((((Zosterops_pallidus:0.0032307347,Zosterops_japonicus:0.0116292191)mrcaott22609ott66394:0.0386805161,(Sylvia_atricapilla:0.0231012889,Sylvia_borin:0.0154195268)mrcaott11419ott830714:0.0497882598)mrcaott1488ott7487:0.0249450688,Pycnonotus_jocosus:0.0527473233)mrcaott1488ott4470:0.0193057750,(Phylloscopus_sibilatrix:0.0560699706,(Cettia_cetti:0.0238810175,Aegithalos_caudatus:0.0579846961)mrcaott5805ott45508:0.0072648785)mrcaott5805ott45321:0.0073445121)mrcaott1488ott5805:0.0080079562,(Riparia_riparia:0.0177073875,Hirundo_rustica:0.0168837582)mrcaott16185ott67916:0.0474185722)mrcaott1488ott16185:0.0000020159,(Hippolais_icterina:0.0335346547,Helopsaltes_ochotensis:0.0563865072)mrcaott44217ott107476:0.0088981095)mrcaott1488ott44217:0.0003368036,(Cisticola_juncidis:0.0750147043,Prinia_subflava:0.0282410202)mrcaott19906ott35027:0.0942874467)mrcaott1488ott17016:0.0249460354,(((Pseudopodoces_humilis:0.0089492764,Parus_major:0.0118197937)mrcaott84656ott875992:0.0016435498,Cyanistes_caeruleus:0.0031728443)mrcaott61147ott84656:0.0019854930,Poecile_atricapillus:0.0103394566)mrcaott2375ott61147:0.0366300373)mrcaott1488ott2375:0.0181286342,(((((((((Turdus_rufiventris:0.0197770481,((Catharus_fuscescens:0.0062170221,Catharus_minimus:0.0000024454)mrcaott545760ott545761:0.0000026050,Catharus_ustulatus:0.0097808295)mrcaott489372ott545760:0.0324696497)mrcaott19467ott252687:0.0243278935,Sialia_sialis:0.0673601700)mrcaott19467ott431648:0.0150633763,((Oenanthe_seebohmi:0.0351120883,Ficedula_albicollis:0.0247790925)mrcaott1566ott22300:0.0103271093,Erithacus_rubecula:0.0350185154)mrcaott1566ott24297:0.0400043521)mrcaott1566ott19467:0.0063310661,Cinclus_mexicanus:0.0270316305)mrcaott1566ott496009:0.0137379109,((Acridotheres_javanicus:0.0052163858,Sturnus_vulgaris:0.0018712624)mrcaott2224ott366470:0.0139419392,Lamprotornis_superbus:0.0123289845)mrcaott2175ott2224:0.0154036115)mrcaott1566ott2175:0.0182564638,(((Thryothorus_ludovicianus:0.0504768084,Polioptila_caerulea:0.0259720843)mrcaott246ott18313:0.0239171957,((Certhia_americana:0.0120176374,Certhia_brachydactyla:0.0017249635)mrcaott697024ott785711:0.0000023438,Certhia_familiaris:0.0034423056)mrcaott157232ott697024:0.0343421613)mrcaott246ott157232:0.0102252869,Sitta_europaea:0.0888201640)mrcaott246ott25638:0.0091320286)mrcaott246ott1566:0.0022095005,Regulus_satrapa:0.0663001226)mrcaott246ott3599436:0.0049485713,(Phainopepla_nitens:0.0665515528,Bombycilla_garrulus:0.0595536098)mrcaott5934ott496029:0.0436554324)mrcaott246ott5934:0.0097745572,((((((((Geothlypis_trichas:0.0269628235,((Quiscalus_mexicanus:0.0034612199,Molothrus_ater:0.0016682748)mrcaott93045ott213448:0.0015242325,(Agelaius_tricolor:0.0000028529,Agelaius_phoeniceus:0.0000023163)mrcaott430627ott617797:0.0019406536)mrcaott93045ott213454:0.0262999938)mrcaott5620ott29804:0.0034220947,Junco_hyemalis:0.0392456236)mrcaott5616ott5620:0.0024154596,((Passerina_amoena:0.0181951203,Cardinalis_cardinalis:0.0186555683)mrcaott23955ott75499:0.0000026973,Pheucticus_melanocephalus:0.0092162574)mrcaott23955ott370813:0.0111849896)mrcaott4088ott5616:0.0064037452,(Emberiza_fucata:0.0303867091,Calcarius_ornatus:0.0223729922)mrcaott28339ott420995:0.0000023467)mrcaott4088ott28339:0.0244729487,(Loxia_sinesciuris:0.0034602479,Loxia_leucoptera:0.0016985293)ott157601:0.0297389131)mrcaott4088ott6366:0.0074817666,Motacilla_alba:0.0570943403)mrcaott4088ott8371:0.0087883726,(Passer_montanus:0.0069257493,Passer_domesticus:0.0068128134)mrcaott9416ott25628:0.0401433920)mrcaott4088ott9416:0.0182480343,(Taeniopygia_guttata:0.0390259349,Vidua_macroura:0.0252902566)mrcaott4083ott52094:0.0065505186)mrcaott4083ott4088:0.0208733009)mrcaott246ott3364:0.0030660482)mrcaott246ott1488:0.0076274345,(Eopsaltria_australis:0.0615886035,Picathartes_gymnocephalus:0.0490576947)mrcaott10351ott193904:0.0040722048)mrcaott246ott10351:0.0187934413,(((((Paradisaea_raggiana:0.0068792199,Parotia_lawesii:0.0157280118)mrcaott23690ott291931:0.0160665354,Struthidea_cinerea:0.0388728537)mrcaott23690ott520286:0.0024202371,((Corvus_brachyrhynchos:0.0053235864,Coloeus_monedula:0.0050776010)ott952596:0.0169607439,(Lanius_collurio:0.0031498192,Lanius_ludovicianus:0.0123971109)mrcaott11462ott290375:0.0510550318)mrcaott4820ott11462:0.0106426223)mrcaott4820ott23690:0.0000029274,Gymnorhina_tibicen:0.0438253975)mrcaott4820ott20998:0.0000029900,((Oriolus_oriolus:0.0453731915,Vireo_altiloquus:0.0448249570)mrcaott19371ott63086:0.0048056023,Falcunculus_frontatus:0.0320968714)mrcaott19371ott89244:0.0000020709)mrcaott4820ott17162:0.0187378914)mrcaott246ott4820:0.0196571718,Entomyzon_cyanotis:0.0591097282)mrcaott246ott5929:0.0247159594,Ptilonorhynchus_violaceus:0.0388987080)mrcaott246ott44866:0.0588056254,(((((((Amazona_aestiva:0.0446021465,Myiopsitta_monachus:0.0269249286)mrcaott165400ott183230:0.0000025853,((((Ara_macao:0.0098786032,Ara_ararauna:0.0077345720)mrcaott300972ott851015:0.0017227066,Guaruba_guarouba:0.0094613314)mrcaott186442ott215177:0.0019303183,Anodorhynchus_hyacinthinus:0.0128866681)mrcaott186442ott416115:0.0000023974,((Pyrrhura_molinae:0.0017237355,Pyrrhura_frontalis:0.0000028863)mrcaott33330ott229282:0.0034552310,Pyrrhura_perlata:0.0000024278)mrcaott33330ott442813:0.0089005465)mrcaott33330ott186442:0.0136500790)mrcaott33330ott165400:0.0117180076,Psittacus_timneh:0.0415226086)mrcaott33330ott300261:0.0028449812,(Agapornis_roseicollis:0.0234835476,(Eclectus_cornelia:0.0064800393,Psittacula_krameri:0.0109944252)mrcaott7116ott445306:0.0196238465)mrcaott7113ott7116:0.0060638761)mrcaott7113ott33330:0.0119908992,(Probosciger_aterrimus:0.0167138634,Eolophus_roseicapilla:0.0225277479)mrcaott58938ott7068761:0.0158831338)mrcaott7113ott58938:0.0096278961,Nestor_notabilis:0.0355303093)ott1020133:0.0496388091,(((Falco_naumanni:0.0035068233,(Falco_rusticolus:0.0017309939,Falco_peregrinus:0.0051949624)mrcaott47588ott48171:0.0016851308)ott786441:0.0352423450,Herpetotheres_cachinnans:0.0275520792)ott212186:0.0224315008,(Cariama_cristata:0.0418501222,((((Sagittarius_serpentarius:0.0406061614,((((Haliaeetus_albicilla:0.0000024744,Haliaeetus_leucocephalus:0.0017196780)mrcaott506937ott773042:0.0034445557,Haliaeetus_pelagicus:0.0017198161)mrcaott327488ott506937:0.0087537249,Astur_gentilis:0.0157287992)mrcaott8285ott11582:0.0076113001,(Spizaetus_tyrannus:0.0069363297,Nisaetus_nipalensis:0.0017398214)mrcaott1858ott317639:0.0067586081)mrcaott1858ott8285:0.0386266746)mrcaott1858ott1036186:0.0121711533,Gymnogyps_californianus:0.0256694950)ott4947835:0.0000023259,((Halcyon_senegalensis:0.1307645616,((Ramphastos_sulfuratus:0.0236050302,Psilopogon_haemacephalus:0.0422228648)mrcaott130076ott291637:0.0223499778,(Dryobates_pubescens:0.0174432701,Melanerpes_aurifrons:0.0250962221)mrcaott45511ott90562:0.0322522657)ott472432:0.0611026567)mrcaott12995ott26078:0.0096286249,(Bucorvus_abyssinicus:0.1094326971,Upupa_marginata:0.1818036603)mrcaott6895ott33689:0.0126549296)mrcaott6895ott12995:0.0104771461)mrcaott1858ott6895:0.0000023368,(((((Caprimulgus_europaeus:0.0611661715,Chordeiles_acutipennis:0.0322584991)mrcaott51276ott275136:0.0463666084,(Calypte_anna:0.1303063544,Podargus_strigoides:0.0521791999)mrcaott5481ott275128:0.0084486172)ott7068066:0.0188011181,(((((((Calonectris_borealis:0.0168151469,Pelecanoides_urinatrix:0.0189353879)mrcaott31011ott85271:0.0013660016,Fulmarus_glacialis:0.0185271397)mrcaott31011ott82196:0.0140953296,Phoebastria_albatrus:0.0462172945)ott452461:0.0083413385,(((Spheniscus_demersus:0.0000028150,Spheniscus_magellanicus:0.0034553278)mrcaott60417ott429622:0.0017881601,Spheniscus_humboldti:0.0033863767)mrcaott60417ott399791:0.0052118113,Eudyptula_minor:0.0017804373)mrcaott60417ott219187:0.0311831353)mrcaott18206ott60413:0.0029347002,((((((Phalacrocorax_carbo:0.0018851538,Urile_pelagicus:0.0069225942)mrcaott9830ott9835:0.0017201683,Nannopterum_auritum:0.0000025414)mrcaott9830ott9831:0.0324777087,Anhinga_anhinga:0.0305837065)mrcaott9830ott443639:0.0029352872,Sula_dactylatra:0.0356815436)mrcaott9830ott117726:0.0178857430,((Cochlearius_cochlearius:0.0193953229,(Butorides_virescens:0.0089709799,Egretta_garzetta:0.0155402801)mrcaott55044ott105529:0.0102673913)mrcaott55044ott154815:0.0219598966,Pelecanus_crispus:0.0633467191)mrcaott55044ott316989:0.0000020311)mrcaott9830ott55044:0.0013576760,Ciconia_maguari:0.0414969928)mrcaott9830ott324158:0.0000028312)mrcaott9830ott18206:0.0026232325,Gavia_stellata:0.0298118025)mrcaott9830ott90560:0.0070040930,(Phaethon_lepturus:0.0566196056,Eurypyga_helias:0.1869083699)mrcaott86672ott330009:0.0055013330)mrcaott9830ott86672:0.0013449358)mrcaott5481ott9830:0.0000023804,((((((Calidris_pugnax:0.0227198802,Arenaria_interpres:0.0296722519)mrcaott24121ott654830:0.0144662629,(Jacana_jacana:0.0815821932,Rostratula_benghalensis:0.0386116556)mrcaott5272ott311533:0.0151677608)mrcaott5272ott24121:0.0163085345,((((Sterna_hirundo:0.0161769136,Rynchops_niger:0.0227143147)mrcaott7639ott738512:0.0000027520,(Chroicocephalus_maculipennis:0.0034756977,Rissa_tridactyla:0.0017339052)mrcaott22965ott154126:0.0107059190)mrcaott7639ott22965:0.0031851801,(((((Uria_aalge:0.0052428737,Uria_lomvia:0.0087187842)ott820019:0.0070221192,Alca_torda:0.0141891436)mrcaott147723ott855485:0.0086065089,Cepphus_grylle:0.0231538058)mrcaott147723ott536766:0.0034759021,Fratercula_arctica:0.0281318301)mrcaott147723ott280907:0.0019180601,Stercorarius_parasiticus:0.0360211663)mrcaott147723ott219032:0.0016995914)mrcaott7639ott147723:0.0140414814,(Dromas_ardeola:0.0269904712,Glareola_pratincola:0.0306849543)mrcaott57833ott383929:0.0106133630)mrcaott7639ott57833:0.0161473608)mrcaott5272ott7639:0.0017930490,((Burhinus_oedicnemus:0.0378976652,Chionis_minor:0.0527971281)mrcaott57827ott57829:0.0122879649,(((Anarhynchus_dealbatus:0.0145889678,Charadrius_vociferus:0.0346495589)mrcaott112937ott129402:0.0009947816,Pluvialis_apricaria:0.0213363161)mrcaott57823ott112937:0.0000027043,(Ibidorhyncha_struthersii:0.0252956160,(Himantopus_leucocephalus:0.0017275316,Himantopus_mexicanus:0.0000022222)ott274627:0.0215666070)mrcaott80080ott293656:0.0029172298)mrcaott57823ott80080:0.0160670629)mrcaott57823ott57827:0.0000020908)mrcaott5272ott57823:0.0087523447,(((Rallus_limicola:0.0578761208,Fulica_atra:0.0380351176)mrcaott7145ott32317:0.0535883441,Heliornis_fulica:0.0789793207)mrcaott7145ott399792:0.0471934535,((Aramus_guarauna:0.0348674033,Grus_nigricollis:0.0253432626)mrcaott257921ott1095362:0.0166795612,Psophia_crepitans:0.0545495423)mrcaott242768ott257921:0.0074322321)mrcaott7145ott242768:0.0213663362)mrcaott5272ott7145:0.0000022690,Opisthocomus_hoazin:0.0724864068)mrcaott5272ott928360:0.0000025993)mrcaott5272ott5481:0.0026353295,((((((Columba_livia:0.0260700858,Streptopelia_turtur:0.0225535816)mrcaott51607ott67614:0.0346344466,Columbina_picui:0.0532858157)mrcaott28925ott45505:0.0063329220,Caloenas_nicobarica:0.0405842868)ott363030:0.0926196993,Pterocles_orientalis:0.0983331871)mrcaott17146ott57819:0.0067806817,((((Geococcyx_californianus:0.0597778039,Crotophaga_sulcirostris:0.0503658010)mrcaott119219ott212182:0.0162289458,Cuculus_canorus:0.0851783604)ott212171:0.0369821012,((Ardeotis_kori:0.0288491662,Tetrax_tetrax:0.0189483958)mrcaott5021ott5027:0.0064898595,Chlamydotis_macqueenii:0.0165043346)mrcaott5021ott323799:0.0481045267)mrcaott5021ott75792:0.0015198952,Crinifer_concolor:0.0681055721)mrcaott5021ott198671:0.0000023760)mrcaott5021ott17146:0.0026671945,(Podilymbus_podiceps:0.0633534611,((((Anseranas_semipalmata:0.0460101885,(((Oxyura_jamaicensis:0.0311933378,Stictonetta_naevosa:0.0263634376)mrcaott88380ott317736:0.0154503789,Nettapus_auritus:0.0134521330)mrcaott88380ott436833:0.0105086860,((Anas_diazi:0.0083682961,(Asarcornis_scutulata:0.0086479008,Aythya_fuligula:0.0069053562)mrcaott30843ott693332:0.0055007443)mrcaott30843ott30845:0.0352975653,(((Anser_indicus:0.0017248940,(Anser_cygnoides:0.0104353779,Anser_brachyrhynchus:0.0069206960)mrcaott164653ott325140:0.0000029404)mrcaott164653ott190897:0.0070000799,Branta_canadensis:0.0087496486)mrcaott75874ott83417:0.0016678644,((Cygnus_atratus:0.0051953723,Cygnus_olor:0.0069328222)mrcaott140312ott140314:0.0016090993,Cygnus_buccinator:0.0174769048)mrcaott140312ott817994:0.0052863317)mrcaott75874ott140312:0.0070076514)mrcaott30843ott75874:0.0040736324)mrcaott30843ott88380:0.0392249435)mrcaott30843ott714464:0.0078955862,Chauna_torquata:0.0436975842)ott241841:0.0098857375,((((Alectoris_rufa:0.0566728563,(Pavo_cristatus:0.0056003894,Pavo_muticus:0.0000025585)ott453587:0.0458531509)mrcaott49310ott51349:0.0098985428,((((Lophura_nycthemera:0.0120576587,Crossoptilon_mantchuricum:0.0068588473)mrcaott53700ott352760:0.0000027405,Phasianus_colchicus:0.0068612770)mrcaott53700ott102722:0.0000025031,Chrysolophus_pictus:0.0034207479)mrcaott53700ott137547:0.0100380321,(Centrocercus_urophasianus:0.0369912656,Meleagris_gallopavo:0.0176722020)mrcaott4765ott446490:0.0061278242)mrcaott4765ott53700:0.0121662359)mrcaott4765ott49310:0.0238661239,(Callipepla_squamata:0.0117022713,Colinus_virginianus:0.0163891142)mrcaott204719ott5860945:0.0905454920)mrcaott4765ott151684:0.0071955546,Numida_meleagris:0.0513669115)mrcaott4765ott104461:0.0764616832)ott5839486:0.0217610084,(((Dromaius_novaehollandiae:0.0072945875,Casuarius_casuarius:0.0243532121)ott589166:0.0275392932,Rhea_americana:0.0859575018)mrcaott84218ott857860:0.0034176231,(Nothoprocta_perdicaria:0.0682534152,Eudromia_elegans:0.0733050273)mrcaott224379ott292461:0.0703256881)mrcaott84218ott167137:0.0865233757)ott241846:0.0169204333)mrcaott246ott92263:0.0011797774)mrcaott246ott5021:0.0000021111)mrcaott246ott5272:0.0017650948)mrcaott246ott1858:0.0000026956)mrcaott246ott3600042:0.0043027164)mrcaott246ott47588:0.0087101203)mrcaott246ott7113:0.0838054818)mrcaott246ott3212:0.0109790584)mrcaott3212ott33874:0.0182984473)mrcaott3212ott8441:0.0267789026)mrcaott8441ott25827:0.0085431235)mrcaott8441ott41222;'

In [3]:
df

,gene,tree
0,A1CF_rna-XM_421561.6,"(Tyrannus_savana:0.1798496778,Oxyruncus_crista..."
1,A4GALT_rna-XM_015290446.2,"(Tyrannus_savana:0.2021741914,(((Pipra_filicau..."
2,A4GNT_rna-XM_426692.5,"(Tyrannus_savana:0.0746472526,Oxyruncus_crista..."
3,AAAS_ENSGALT00000088467.2,"(Pipra_filicauda:0.0079899640,Lepidothrix_velu..."
4,AACS_ENSGALT00000004577.6,"(Tyrannus_savana:0.0491120196,Oxyruncus_crista..."
...,...,...
3718,ZFPM2_rna-XM_418380.6,"(Tyrannus_savana:0.0267434121,Oxyruncus_crista..."
3719,ZFYVE19_ENSGALT00000013788.6,"(Tyrannus_savana:0.0570726543,Oxyruncus_crista..."
3720,ZFYVE1_rna-XM_015287087.2,"(Tyrannus_savana:0.0404787967,Oxyruncus_crista..."
3721,ZFYVE21_ENSGALT00000060862.2,"(Tyrannus_savana:0.0573798288,Oxyruncus_crista..."
3722,ZFYVE26_rna-XM_004941715.3,"(Tyrannus_savana:0.0620670807,Oxyruncus_crista..."